export const lastTechnologies = [
  "JS, TS, HTML, CSS, SCSS",
  "Node.js, Nest.js, Express, Koa, Strapi CMS",
  "MySQL, PostgreSQL, MongoDB, Redis, Elasticsearch, Firebase",
  "TypeORM, Mongoose",
  "REST, GraphQL, WebSocket",
  "IIPImage, Heroku",
  "RabbitMQ, Hatchet",
  "Docker, Nginx",
  "Stripe, Bank integrations/APIs",
  "Swagger",
  "Unit Testing, E2E Testing",
  "React, Next.js",
  "Git",
  "Familiar with: React Native, Expo, Angular, Vue, Python, Flask, Tauri, K6",
];
