export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link
          rel="shortcut icon"
          href="/images/favicon.png"
          type="image/x-icon"
        />
      <body>{children}</body>
    </html>
  );
}
